### ISSUE TITLE
半监督方式训练monoskd

### ISSUE THREAD

**Issue by aqr1961** [Senwang98/MonoSKD#10]
为了进一步提升检测精度，我正在考虑使用KITTI RAW数据集对monoskd进行半监督扩展。在此过程中，我遇到了一些技术问题，希望能得到您的指导与建议：

在半监督训练中，为了获取与RGB单目图像对应的密集深度图，我应该直接使用KITTI Depth Completion数据集中的gt图，还是应该从LIDAR点云补全获得？哪种方式更为合适？
关于伪标签的生成，我是否可以参考LPCG的模式？这样的方法是否可行，请问您有何高见？
非常感谢您的帮助和支持。

**Comment by Senwang98** [comment]
kitti raw提供了lidar数据，可以根据MonoDistill的思路补全点云
LPCG的思路可行的
