### ISSUE TITLE
Can you provide the visualization code?

### ISSUE THREAD

**Issue by aqr1961** [Senwang98/MonoSKD#3]
Excuse me, could you please provide me with the code for visualizing the results in your paper ?
![1703428841335](https://github.com/Senwang98/MonoSKD/assets/96245592/b8da6494-937b-4c94-b10e-d12a2fcac9fb)

**Comment by Senwang98** [comment]
You can use this script from PatchNet: https://github.com/xinzhuma/patchnet/blob/master/tools/visualization.py
