### ISSUE TITLE
some question;

### ISSUE THREAD

**Issue by aqr1961** [Senwang98/MonoSKD#5]
感谢您对于3d目标检测领域的重要贡献。
现在，我有一些关于代码方面的疑问，
1.spearman_loss中，为什么只对feature_pred_down使用了软排序将其转换为等级系数，而没有对feature_target_down进行相应的排序操作呢？我理解计算斯皮尔曼相关系数需要先将X和Y都转换为等级变量，然后再去计算皮尔逊相关系数。
  feature_target_down = feature_target_down.reshape(B, -1)您在展平的时候，每个样本的所有通道上的所有位置的特征都被展平了；我想问一下对于每一个样本而言是否可以考虑，仅将对应通道上的特征进行排序，而不是将所有通道混合起来考虑，这样是否更合理一些呢？
2.compute_backbone_resize_affinity_loss中，文献中给出的Aij=fi^T*fj/(||fi||2*||fj||2),但是您提供的代码中，Aij=fi^T*fj而没有分母项，我阅读过monodistill代码，里面也没有分母项，对于这里我有疑问，去掉分母项后对于精度的影响会有多大呢，为什么要去掉分母项呢？

**Comment by aqr1961** [comment]
还有，lib/datasets/kitti.py代码中：
if self.split != 'test':
            depth_map = d_trans.astype(np.float32) / 256.0 
            depth_map = depth_map * aug_scale
            depth_map = np.expand_dims(depth_map, 2)
            depth_map = np.repeat(depth_map, 3, 2)
            depth_map = depth_map / 80.0  #大致归一化到[0,1]区间内
            # depth_map = (depth_map - self.gt_depth_mean) / self.gt_depth_std
            depth_map = depth_map.transpose(2, 0, 1)  # C * H * W

depth_map = d_trans.astype(np.float32) / 256.0 这里似乎不必再去除以256，因为在之前已经经历了这样的操作，不知道我分析的是否正确，请您斧正。

**Comment by Senwang98** [comment]
1. 计算成本过大
2. 影响并不大，分母类似一个loss的reweight
3. 确实这里应该只有一个256，这里不除以任何256也不影响teacher蒸馏，但压低数值会让teacher相对稳定些

**Comment by aqr1961** [comment]
好的谢谢您，后面两个我理解了。第一个是不是：在计算斯皮尔曼相关系数的时候，实际上只需要对pred和target中的一组值进行软排序就可以吧？（原则上是需要两个都进行软排序的）这里去除以一个系数的含义应该只是让蒸馏更稳定一些吧，因为标准的斯皮尔曼计算没有这一步骤：feature_pred_down / feature_pred_down.shape[-1])？

**Comment by Senwang98** [comment]
@aqr1961 
因为同时对pred与gt都做排序的话计算成本double了，可以我转化成只做一次soft rank，是等价的
