### ISSUE TITLE
About depth data.

### ISSUE THREAD

**Issue by ruiw0w** [Senwang98/MonoSKD#6]
感谢您对于3d目标检测领域的重要贡献，很荣幸阅读您的文章。
我对数据处理部分有疑问，
在kitti.py中：
        self.gt_depth_mean = np.array([8.765, 8.765, 8.765], dtype=np.float32)
        self.gt_depth_std = np.array([11.275, 11.275, 11.275], dtype=np.float32)
这是对训练集中所有深度图进行统计分析得到的数值吗？具体是如何计算的？
期待您的回复，感谢！

**Comment by Senwang98** [comment]
@ruiw0w 
哈喽，这部分的计算方式跟rgb图片计算一致，可以参考网上的博客修改：https://blog.csdn.net/dcrmg/article/details/102467434

By the way，根据我之前的经验，训练teacher网络是否做mean与std的归一化对蒸馏的结果影响不大，即使发现做了归一化之后teacher性能提升，但是教师网络提升并不一定导致最终蒸馏性能提升。

**Comment by ruiw0w** [comment]
我会参照此方式进行修改。您所给的建议我会注意，感谢！

**Comment by ruiw0w** [comment]
您好，我根据您所提供的参考建议进行计算，数据集大小为7481，会导致爆内存，我修改了计算逻辑，统计所有像素值及像素点数量进行计算，如下：
imgs_path = '/home/xurx/下载/depth_dense/'
imgs_path_list = os.listdir(imgs_path)

sum_pixels = 0
sum_squared_pixels = 0
n_pixels = 0

for item in tqdm(imgs_path_list):
    img_path = os.path.join(imgs_path, item)
    img = cv2.imread(img_path, cv2.IMREAD_UNCHANGED)
    if img is not None:
        img = img.astype(np.float32) / 255.  # 如果需要，进行归一化

        sum_pixels += np.sum(img)
        sum_squared_pixels += np.sum(np.square(img))
        n_pixels += img.size

mean = sum_pixels / n_pixels
std = np.sqrt((sum_squared_pixels / n_pixels) - (mean ** 2))

print(f"Dataset Mean: {mean}")
print(f"Dataset Std Dev: {std}")

所得到的结果：
Dataset Mean: 19.74753719237534
Dataset Std Dev: 16.410785733290904
我不知道哪里出现了问题，是否在计算之前进行缩放操作？希望能够得到您的帮助，感谢！
