### ISSUE TITLE
请问为什么教师-学生训练中还需要使用 HTL

### ISSUE THREAD

**Issue by romantic-black** [Senwang98/MonoSKD#7]
HTL 默认在前 5 轮时只训练无依赖的任务，这可能导致深度预测任务出现问题，在单独训练教师和学生时我认为可以使用，但在合并训练时感觉没必要再使用

**Comment by Senwang98** [comment]
之前实验中，HTL在蒸馏时能稍微提一点性能，不是必须的；MonoDistill并没有透露GUPNet蒸馏细节，因此我保留了这部分
